
try{
    console.log(document);
} catch(e){
    console.log('Ocorreu um erro!');
}